/* Stabiele IDs behouden bij toekomstige uitbreidingen: bestaande voortgang blijft gekoppeld. */
(function (root) {
  const sources = {
    L: 'litratuur.txt — aangeleverde samenvatting van Okasha en Pfeffer & Sutton, niet de originele publicaties',
    C: 'College 1 voor Canvas.pdf',
    Q: 'Screenshots Week 1 Quiz (20260904) — vragen 1 t/m 10'
  };
  const flashcards = [
    ['Wetenschap','Wat probeert wetenschap te bereiken?','De wereld systematisch begrijpen, verklaren en voorspellen met behulp van redenering, observaties en toetsing. Een wetenschappelijk uiterlijk is op zichzelf geen bewijs van betrouwbaarheid.','L; C p. 31, 41'],
    ['Demarcatie','Wat is het demarcatieprobleem?','De vraag hoe we wetenschap van niet-wetenschap, waaronder pseudowetenschap, onderscheiden. Eén eenvoudige checklist of criterium legt die grens niet volledig vast.','Q 2–3; C p. 16, 31'],
    ['Pseudowetenschap','Waarom maakt technisch taalgebruik een theorie nog niet wetenschappelijk?','Jargon kan de indruk van wetenschap wekken zonder dat beweringen empirisch toetsbaar zijn. Vraag welke waarnemingen de claim ondersteunen of ermee in strijd zouden zijn.','Q 1'],
    ['Falsifieerbaarheid','Wat betekent falsifieerbaarheid bij Popper?','Er moet in principe een mogelijke waarneming zijn die met de theorie in strijd is. Falsifieerbaar betekent dus weerlegbaar, niet dat de theorie al onwaar is.','L'],
    ['Falsifieerbaarheid','Wat is het verschil tussen falsifieerbaar en gefalsifieerd?','Falsifieerbaar: een weerlegging is in principe mogelijk. Gefalsifieerd: er is daadwerkelijk een weerlegging vastgesteld, gegeven de relevante aannames en betrouwbare waarnemingen.','L; C p. 16'],
    ['Falsifieerbaarheid','Waarom bewijzen duizend witte zwanen niet dat alle zwanen wit zijn?','Niet alle gevallen zijn waargenomen. Een volgende zwaan kan zwart zijn. Een betrouwbaar vastgesteld zwart exemplaar is wel een tegenvoorbeeld voor de universele uitspraak.','L'],
    ['Demarcatie','Waarom is falsifieerbaarheid geen eenvoudige definitieve oplossing voor demarcatie?','Het onderscheid blijft betekenisvol, maar wetenschappelijke praktijken zijn te veelzijdig om met één eenvoudig criterium volledig te beoordelen. Een strikte checklist kan legitieme wetenschap uitsluiten.','Q 2–3'],
    ['Redeneren','Wat is een premisse?','Een uitgangsuitspraak van een redenering. De conclusie wordt op basis van één of meer premissen afgeleid.','L'],
    ['Deductie','Wat maakt een deductieve redenering geldig?','Als de premissen waar zijn, kan de conclusie niet onwaar zijn. Geldigheid gaat over het logische verband; zij garandeert niet dat de premissen feitelijk kloppen.','L; C p. 35–36'],
    ['Deductie','Is een logisch geldige redenering automatisch waar over de wereld?','Nee. Een geldige redenering kan vertrekken van onware aannames. Voor een gegarandeerd ware conclusie zijn ook ware premissen nodig.','L; C p. 36, 39'],
    ['Deductie','Geef een voorbeeld van deductie.','Alle leden van team A hebben een toegangspas. Noor is lid van team A. Dus Noor heeft een toegangspas. Als beide premissen waar zijn, volgt de conclusie noodzakelijk.','L (nieuw toepassingsvoorbeeld)'],
    ['Inductie','Wat is inductief redeneren?','Van waargenomen gevallen naar een bredere uitspraak of voorspelling over niet-waargenomen gevallen gaan. De conclusie volgt niet met logische noodzaak.','L; Q 4–5'],
    ['Inductie','Geef een managementvoorbeeld van inductie.','In vijf onderzochte vestigingen daalt het verzuim na een maatregel. Je verwacht dat die maatregel ook elders zal helpen. Dat gaat verder dan de onderzochte gevallen en blijft onzeker.','L; C p. 16 (nieuw toepassingsvoorbeeld)'],
    ['Inductie','Wat is het probleem van inductie?','Beperkte waarnemingen en eerdere ervaringen garanderen niet logisch dat een algemene uitspraak of een voorspelling over nieuwe gevallen waar is.','L; Q 4'],
    ['Inductie','Verdwijnt het probleem van inductie bij een heel grote steekproef?','Nee. Meer relevante waarnemingen kunnen de ondersteuning verbeteren, maar maken een conclusie over niet-waargenomen gevallen niet logisch zeker.','L; Q 4'],
    ['Redeneren','Wat is het beslissende verschil tussen inductie en deductie?','Bij geldige deductie garanderen ware premissen een ware conclusie. Bij inductie kan de conclusie onwaar zijn terwijl de waarnemingen waarop zij rust kloppen.','L'],
    ['Rationalisme','Wat is filosofisch rationalisme?','De opvatting dat de rede de belangrijkste bron van betrouwbare kennis is. Het benadrukt logische principes, deductie en scepsis tegenover misleidende zintuiglijke indrukken.','C p. 32, 35'],
    ['Rationalisme','Welke drie rationalisten noemen de slides?','Descartes, Spinoza en Leibniz.','C p. 35'],
    ['Rationalisme','Wat drukt Descartes uit met Cogito, ergo sum?','Ik denk, dus ik ben. Het denken vormt hier een vertrekpunt voor zekerheid in plaats van simpelweg op de zintuigen te vertrouwen.','C p. 35'],
    ['Rationalisme','Wat zijn een sterkte en een risico van modellen in de bedrijfskunde?','Sterkte: aannames expliciet maken en gevolgen logisch afleiden. Risico: een logisch samenhangend model kan op onjuiste aannames over de werkelijkheid berusten.','C p. 36'],
    ['Empirisme','Wat is filosofisch empirisme?','De opvatting dat ervaring de belangrijkste bron van kennis is. Observatie en experiment confronteren beweringen met de werkelijkheid.','C p. 38'],
    ['Empirisme','Welke drie empiristen noemen de slides?','Locke, Berkeley en Hume.','C p. 38'],
    ['Empirisme','Hoe verschillen rationalisten en empiristen over aangeboren ideeën?','Rationalisten laten ruimte voor kennisstructuren of ideeën die niet uit ervaring komen. Empiristen staan sceptisch tegenover aangeboren kennis en benadrukken ervaring.','C p. 35, 38'],
    ['Wetenschappelijke cyclus','Waarom heeft moderne wetenschap zowel rede als ervaring nodig?','Logische samenhang garandeert niet dat een theorie bij de wereld past. Omgekeerd interpreteren gegevens zichzelf niet. Redenering en empirische toetsing vullen elkaar aan.','C p. 39–41'],
    ['Wetenschappelijke cyclus','Welke rol spelen inductie en deductie in de wetenschappelijke cyclus?','Inductie helpt patronen uit observaties te generaliseren. Deductie helpt uit een theorie toetsbare verwachtingen af te leiden. Nieuwe observaties kunnen aanleiding geven tot bijstelling.','C p. 40–41'],
    ['Bewijs interpreteren','Wat betekent: bewijs interpreteert zichzelf niet?','Gegevens vereisen redenering over context, aannames en alternatieve verklaringen. Een correct waargenomen verband kan verkeerd worden uitgelegd.','C p. 21–24'],
    ['Simpsons paradox','Wat laat het rookvoorbeeld over Simpsons paradox zien?','In de samengevoegde gegevens hebben rokende tieners grotere longcapaciteit, terwijl binnen iedere leeftijdsgroep meer roken samenhangt met lagere longcapaciteit. Leeftijd beïnvloedt beide variabelen.','C p. 21–23'],
    ['Causaliteit','Waarom bewijst een stijging na een maatregel niet dat de maatregel de oorzaak is?','Er kunnen gelijktijdige veranderingen of andere verklaringen zijn, zoals een groeiende markt of ander personeel. Alleen de volgorde in de tijd sluit die verklaringen niet uit.','L'],
    ['Hulphypotheses','Wat is een hulphypothese bij het toetsen van een theorie?','Een aanvullende aanname die nodig is om een voorspelling aan een test te verbinden, bijvoorbeeld dat de maatregel correct is uitgevoerd. Een tegenvallend resultaat kan ook daarmee samenhangen.','C p. 16'],
    ['Bewijs en overtuigingen','Wat betekent responsiveness to evidence?','Bereid zijn overtuigingen en handelen bij te stellen als relevante bevindingen daartoe aanleiding geven. Bewijs verzamelen zonder erop te reageren is onvoldoende.','C p. 16, 25; L'],
    ['Semmelweis','Welke interventie en uitkomst beschrijven de slides bij Semmelweis?','Handen wassen met chloorkalk; daarna daalde de moedersterfte sterk. De casus laat ook zien dat overtuigend praktisch bewijs niet vanzelf wordt geaccepteerd.','C p. 17–19'],
    ['John Snow','Hoe botste John Snows verklaring van cholera met de heersende theorie?','Snow wees op besmet water en het patroon van sterfgevallen rond een waterpomp. Dat botste met de miasmatheorie, die ziekte aan slechte lucht toeschreef.','C p. 20'],
    ['Filosofie','Wat onderzoekt filosofie volgens de slides?','Overtuigingen, aannames en concepten systematisch en kritisch: wat geloven we, waarom, is de rechtvaardiging voldoende en wat zou onze mening veranderen?','C p. 30'],
    ['Geschiedenis','Hoe droeg de drukpers volgens het college bij aan kritisch onderzoek?','Ideeën konden breder worden verspreid, vergeleken en bekritiseerd. Daardoor werden fouten zichtbaarder en werd kennis publiekelijk betwistbaarder.','C p. 29'],
    ['Evidence-based management','Wat is evidence-based management (EBM)?','Managementbeslissingen baseren op het beste beschikbare bewijs en kennis blijven bijstellen. Het doel is betere beslissingen en prestaties, niet onfeilbaarheid.','L; Q 10'],
    ['Evidence-based management','Waarom zijn intuïtie en persoonlijke anekdotes onvoldoende als enige basis?','Ze kunnen beperkt of selectief zijn en hoeven niet representatief te zijn. Ervaring kan aanleiding geven tot een vraag, maar moet kritisch worden vergeleken met ander relevant bewijs.','L; Q 6'],
    ['Casual benchmarking','Wat betekent casual benchmarking?','Een praktijk van een succesvol bedrijf overnemen omdat het bedrijf succesvol is, zonder voldoende te onderzoeken of die praktijk het succes veroorzaakte en in de eigen context past.','Q 7; L'],
    ['Evidence-based management','Waarom garandeert succes in organisatie A geen succes in organisatie B?','Organisaties kunnen verschillen in personeel, klanten, cultuur, technologie en markt. De overdraagbaarheid van een praktijk moet worden onderzocht.','L; C p. 16'],
    ['Barrières voor EBM','Noem drie culturele of psychologische barrières voor EBM.','Overmatig vertrouwen op conventionele wijsheid, eigen ervaring als superieur beschouwen en weigeren kleinschalig te experimenteren.','Q 6, 8'],
    ['Prikkels','Hoe kunnen beloningen EBM ondermijnen?','Als vooral kortetermijnresultaten worden beloond, kan zorgvuldig toetsen en leren worden verdrongen, ook als er weinig bewijs is voor de gebruikte aanpak.','Q 9'],
    ['Evidence-based management','Waarom maakt EBM het oordeel van een manager niet overbodig?','Bewijs moet worden beoordeeld op kwaliteit en toepasbaarheid in de eigen situatie. Beslissingen blijven afwegingen onder onzekerheid.','L; Q 10'],
    ['Verbinding literatuur','Hoe sluiten Okasha en Pfeffer & Sutton op elkaar aan?','Okasha behandelt hoe kennis en conclusies gerechtvaardigd worden. Pfeffer & Sutton passen een kritische omgang met bewijs toe op managementbeslissingen.','L']
  ];
  // Het juiste antwoord staat in de brondata vooraan; de oefeninterface moet opties schudden.
  const quizzes = [
    ['Pseudowetenschap','Een adviseur gebruikt ingewikkelde termen, maar kan geen uitkomst noemen die zijn claim tegenspreekt. Wat is het kernprobleem?',['De claim mist een duidelijke mogelijkheid tot empirische weerlegging.','De claim bevat te weinig wiskundige formules.','De adviseur probeert iets te verklaren in plaats van te voorspellen.','De adviseur gebruikt vaktermen.'],'Vaktermen zijn niet het probleem op zichzelf. Doorslaggevend is hier dat de bewering aan iedere mogelijke uitkomst kan worden aangepast.','Q 1; L'],
    ['Demarcatie','Een student stelt: alleen onderzoek met laboratoriumexperimenten is wetenschap. Wat is de beste kritiek?',['Deze eis kan legitieme wetenschappen uitsluiten.','Ieder vakgebied met veel volgers is wetenschap.','Wetenschap heeft nooit experimenten nodig.','Wetenschap en pseudowetenschap verschillen uitsluitend in populariteit.'],'Een eenvoudige methodechecklist vangt de verscheidenheid aan wetenschappelijk onderzoek niet volledig.','Q 2–3'],
    ['Demarcatie','Iemand zegt: omdat geen enkel eenvoudig criterium volstaat, bestaat het onderscheid tussen wetenschap en pseudowetenschap niet. Welke reactie past bij de quizstof?',['Het onderscheid kan betekenisvol zijn zonder één sluitend eenvoudig criterium.','Het onderscheid bestaat alleen als Popper altijd gelijk heeft.','Een gebrek aan één criterium maakt alle claims even betrouwbaar.','Het onderscheid hangt uitsluitend af van de opleiding van de spreker.'],'Moeilijk af te bakenen betekent niet betekenisloos. De quiz waarschuwt zowel voor een simpele oplossing als voor het volledig opgeven van het onderscheid.','Q 3'],
    ['Falsifieerbaarheid','Welke uitspraak is het duidelijkst falsifieerbaar?',['Iedere werknemer in dit team heeft vandaag vóór negen uur ingelogd.','Een onzichtbare kracht verklaart iedere mogelijke uitkomst.','Onze methode werkt altijd, behalve wanneer zij niet werkt.','Succes verschijnt zodra de energie op een onmeetbare manier klopt.'],'Een betrouwbaar vastgesteld teamlid dat niet vóór negen uur inlogde is een tegenvoorbeeld. De andere claims ontwijken duidelijke toetsing.','L (nieuw toepassingsvoorbeeld)'],
    ['Falsifieerbaarheid','Een degelijk tegenvoorbeeld weerlegt de uitspraak dat alle vestigingen winstgevend zijn. Wat volgt?',['De universele uitspraak is onjuist.','Alle vestigingen maken verlies.','Geen enkele uitspraak over winst is toetsbaar.','Er zijn onvoldoende gegevens om de universele uitspraak te weerspreken.'],'Eén verliesgevende vestiging weerlegt alle vestigingen zijn winstgevend, maar zegt niet dat alle vestigingen verlies maken.','L (nieuw toepassingsvoorbeeld)'],
    ['Deductie','Alle projecten in categorie X worden gecontroleerd. Project Delta behoort tot X. Wat volgt deductief?',['Project Delta wordt gecontroleerd.','Alle gecontroleerde projecten behoren tot X.','Project Delta is succesvol.','Waarschijnlijk behoren alle projecten tot X.'],'De conclusie past de algemene premisse toe op Delta. De omkering en een conclusie over succes volgen niet uit deze premissen.','L'],
    ['Deductie','Een model redeneert zonder logische fouten vanuit de aanname dat iedere klant alleen de laagste prijs kiest. Is de voorspelling daardoor zeker juist?',['Nee, de aanname over klanten kan onjuist zijn.','Ja, logische geldigheid garandeert dat aannames kloppen.','Ja, zolang het model voldoende formules bevat.','Nee, deductie kan nooit een noodzakelijke conclusie opleveren.'],'Geldigheid garandeert alleen een ware conclusie als de premissen ook waar zijn.','C p. 36, 39; L'],
    ['Inductie','Een onderzoeker vindt bij dertig teams een vergelijkbaar patroon en verwacht dat het ook bij andere teams optreedt. Welke redenering is dit?',['Inductie, omdat de conclusie verder gaat dan de onderzochte teams.','Deductie, omdat er dertig teams zijn onderzocht.','Falsificatie, omdat ieder patroon een theorie weerlegt.','Een logische zekerheid, omdat het patroon herhaald is.'],'De stap van onderzochte naar niet-onderzochte gevallen is inductief. Herhaling maakt die stap niet deductief geldig.','Q 4–5; L'],
    ['Inductie','Alle tot nu toe onderzochte machines van een type waren betrouwbaar. Waarom is gegarandeerd betrouwbaar bij iedere toekomstige machine te sterk?',['De conclusie omvat niet-waargenomen gevallen.','Herhaalde observaties kunnen geen enkele steun bieden.','Alle inductieve conclusies zijn feitelijk onwaar.','Deductie wordt ongeldig zodra een machine wordt onderzocht.'],'Inductief bewijs kan ondersteunen zonder een universele of toekomstige uitspraak logisch te garanderen.','Q 4; L'],
    ['Inductie','Een directeur zegt: deze aanpak werkte in twee bedrijven, dus hij werkt zeker in ons bedrijf. Waar zit de overschatting?',['De stap naar een nieuwe context wordt als logisch zeker gepresenteerd.','Er wordt een noodzakelijke conclusie uit ware algemene premissen getrokken.','De directeur gebruikt waarnemingen, en dat mag niet bij management.','Twee bedrijven kunnen per definitie geen relevante informatie opleveren.'],'Eerdere ervaringen kunnen relevant zijn, maar verschillen in context blijven belangrijk.','L; C p. 16'],
    ['Rationalisme','Een student benadrukt deductie, aangeboren ideeën en wantrouwen tegenover de zintuigen. Welke stroming past het best?',['Rationalisme.','Empirisme.','Casual benchmarking.','Een uitsluitend op ervaring gebaseerde kennisleer.'],'Deze combinatie behoort in de slides bij rationalisme. Empirisme legt juist het accent op ervaring.','C p. 35, 38'],
    ['Empirisme','Een onderzoeker zegt: een sluitende redenering is niet genoeg; we moeten kijken wat er werkelijk gebeurt. Welk accent legt zij?',['Een empiristisch accent op observatie en toetsing.','De afwijzing van iedere mogelijke observatie.','De zekerheid dat aangeboren ideeën alle kennis leveren.','De stelling dat logisch samenhangende theorieën altijd waar zijn.'],'Zij eist confrontatie met ervaring. Dit betekent niet dat logische redenering onbelangrijk wordt.','C p. 37–39'],
    ['Wetenschappelijke cyclus','Een onderzoeker leidt uit een theorie een verwachting af en verzamelt vervolgens gegevens. Wat is de eerste stap?',['Deductie van een toetsbare verwachting.','Inductie vanuit de nog niet verzamelde gegevens.','Bewijs dat de theorie definitief waar is.','Het uitsluiten van iedere hulphypothese.'],'Van een theorie naar een verwachting redeneren is de deductieve kant van de cyclus; daarna volgt empirische toetsing.','C p. 40'],
    ['Wetenschappelijke cyclus','Een team vindt in metingen een patroon, vormt een theorie en test nieuwe voorspellingen. Welke omschrijving past het best?',['Een wisselwerking tussen inductie, deductie en observatie.','Zuiver rationalisme zonder waarneming.','Uitsluitend deductie van begin tot eind.','Een proces waarin toetsing na theorievorming overbodig is.'],'De cyclus verbindt generaliseren uit observaties met het afleiden en toetsen van nieuwe verwachtingen.','C p. 40–41'],
    ['Simpsons paradox','In totaal hebben deelnemers aan een training hogere scores. Binnen elke ervaringsgroep scoren deelnemers juist lager. Wat moet je eerst onderzoeken?',['Hoe ervaring samenhangt met deelname en scores.','Waarom het totaalgemiddelde altijd de oorzaak bewijst.','Hoe je de uitkomsten per ervaringsgroep kunt negeren.','Waarom ieder verschil aantoont dat de gegevens vervalst zijn.'],'Een derde variabele kan een omkering tussen samengevoegde en uitgesplitste patronen helpen verklaren, zoals leeftijd in het collegevoorbeeld.','C p. 21–23 (nieuwe casus)'],
    ['Causaliteit','Na invoering van een bonus stijgt de omzet, terwijl ook de hele markt sterk groeit. Wat is de beste conclusie?',['De stijging alleen toont niet aan dat de bonus de oorzaak is.','De bonus heeft bewezen de volledige stijging veroorzaakt.','De marktgroei bewijst dat de bonus geen enkel effect had.','De omzetmeting moet onjuist zijn.'],'Er is een alternatieve verklaring. Zonder verdere vergelijking kun je het afzonderlijke effect van de bonus niet uit deze stijging afleiden.','L'],
    ['Hulphypotheses','Een interventie levert geen verwacht resultaat op, maar de uitvoering week sterk af van het plan. Wat is een relevante vervolgvraag?',['Faalde de theorie of een aanname over correcte uitvoering?','Hoe bewijst dit dat geen theorie ooit te toetsen is?','Waarom is de theorie nu automatisch waar?','Welke succesvolle concurrent kunnen we zonder onderzoek kopiëren?'],'Tests steunen ook op aanvullende aannames. Die moet je onderzoeken; afwijkende uitvoering is geen automatische vrijbrief voor de theorie.','C p. 16'],
    ['Semmelweis','Een organisatie ziet sterke aanwijzingen dat een werkwijze schade vermindert, maar weigert verandering omdat gevestigde autoriteiten haar afwijzen. Welke les uit het college past?',['Bewijs beschikbaar hebben garandeert nog niet dat mensen hun overtuigingen aanpassen.','Autoriteit vormt altijd sterker bewijs dan observaties.','Een werkzame interventie vereist vooraf een volledig juiste theorie.','Gegevens kunnen nooit botsen met bestaande overtuigingen.'],'De casus Semmelweis toont de afstand tussen praktisch bewijs en acceptatie.','C p. 17–19'],
    ['John Snow','Een patroon rond een waterbron botst met de overtuiging dat slechte lucht ziekte veroorzaakt. Wat illustreert deze casus in het college?',['Empirische bevindingen kunnen een gevestigde verklaring uitdagen.','Een gevestigde theorie mag observaties altijd terzijde schuiven.','Ruimtelijke patronen leveren per definitie deductieve zekerheid.','Alleen autoriteit kan bepalen of waarnemingen relevant zijn.'],'De slides gebruiken Snow om de spanning tussen theorie en bewijs te tonen; gegevens moeten serieus worden onderzocht.','C p. 20, 37'],
    ['Casual benchmarking','Een directeur kopieert het beoordelingssysteem van een marktleider, uitsluitend omdat die marktleider winstgevend is. Wat doet hij?',['Casual benchmarking.','Een gecontroleerd experiment.','Een deductief bewijs van overdraagbaarheid.','Een systematische toets van alternatieve verklaringen.'],'Het succes van het bedrijf bewijst niet dat juist dit beoordelingssysteem het veroorzaakte of elders werkt.','Q 7; L'],
    ['Evidence-based management','Een consultant verdedigt een ingreep met: ik doe dit al twintig jaar. Welke reactie past het best bij EBM?',['Welke resultaten en onderzoeken ondersteunen deze ingreep in onze situatie?','Ervaring is per definitie waardeloos.','Twintig jaar ervaring maakt toetsing overbodig.','We volgen alleen de bekendste consultant.'],'Ervaring kan informatie opleveren, maar vervangt niet het kritisch onderzoeken van effectiviteit en context.','Q 6; L'],
    ['Barrières voor EBM','Welke situatie is vooral een culturele of psychologische barrière voor EBM?',['Een manager weigert pilots omdat zijn ervaring volgens hem al voldoende bewijs is.','Er is tijdelijk een defect in de computer voor data-analyse.','Een spreadsheetbestand is per ongeluk niet opgeslagen.','Een vergaderruimte is niet beschikbaar.'],'Het overmatige vertrouwen in eigen ervaring en de weigering te testen zijn houdingen. De andere opties zijn praktische problemen.','Q 8'],
    ['Prikkels','Een bonus wordt alleen bepaald door de omzet van deze maand; tijd om effecten te onderzoeken telt niet mee. Welk risico past bij de stof?',['Kortetermijnbeloningen kunnen zorgvuldig leren en toetsen verdringen.','Alle managers zullen daardoor vanzelf experimenten publiceren.','Prestatiemetingen verdwijnen hierdoor noodzakelijk volledig.','Iedere beloning maakt evidence-based werken onmogelijk.'],'De prikkel kan onmiddellijke resultaten boven het toetsen van de aanpak plaatsen. Dat is een risico, geen wet dat alle beloningen verkeerd zijn.','Q 9'],
    ['Evidence-based management','Wat is het meest passende doel van EBM?',['Betere organisatieprestaties via beslissingen op basis van het beste beschikbare bewijs.','Alle beslissingen onfeilbaar maken.','Het oordeel van managers volledig vervangen.','Geen rekening meer houden met onzekerheid.'],'EBM verbetert de basis voor keuzes; het elimineert onzekerheid en professionele afwegingen niet.','Q 10; L'],
    ['Evidence-based management','Onderzoek uit grote fabrieken lijkt gunstig, maar jouw organisatie is een klein ontwerpteam. Wat is de beste volgende stap?',['Onderzoeken hoe relevant het bewijs is en zo mogelijk lokaal zorgvuldig toetsen.','De aanpak zonder aanpassing invoeren omdat onderzoek altijd universeel geldt.','Al het onderzoek verwerpen omdat organisaties verschillen.','Alleen nagaan of de auteurs beroemd zijn.'],'Contextverschillen vragen om beoordeling van toepasbaarheid, niet automatisch kopiëren of automatisch afwijzen.','L'],
    ['Bewijs en overtuigingen','Een manager vraagt vooraf welke uitkomst reden is om zijn favoriete aanpak te stoppen. Welke houding laat hij zien?',['Bereidheid om op bewijs te reageren.','De zekerheid dat zijn aanpak onjuist is.','Weigering om de aanpak toetsbaar te maken.','Het idee dat persoonlijk vertrouwen voldoende is.'],'Vooraf nadenken over tegenbewijs maakt bijstellen mogelijk. Het is iets anders dan vooraf aannemen dat een aanpak faalt.','C p. 15–16, 30'],
    ['Geschiedenis','Waarom ondersteunt een bredere verspreiding van ideeën via de drukpers kritisch onderzoek?',['Meer mensen kunnen claims vergelijken, fouten herkennen en kritiek verspreiden.','Gedrukte uitspraken worden daardoor noodzakelijk waar.','Waarnemingen zijn vanaf dat moment overbodig.','Publicatie maakt iedere auteur tot onbetwistbare autoriteit.'],'Openbaarheid en uitwisseling faciliteren kritiek, maar garanderen geen waarheid.','C p. 29'],
    ['Verbinding literatuur','Een manager vraagt of een kleine steekproef genoeg rechtvaardiging geeft om beleid voor alle vestigingen in te voeren. Welke verbinding legt hij?',['Het inductieprobleem verbinden met evidence-based management.','Een universele zekerheid afleiden uit een persoonlijke voorkeur.','Wetenschapsfilosofie losmaken van managementbeslissingen.','De conclusie dat onderzoek nooit bruikbaar is.'],'Hij beoordeelt hoe ver bewijs een conclusie ondersteunt en gebruikt die afweging bij een praktische beslissing.','L; Q 4, 10']
  ];
  const bank = {
    schemaVersion: 1,
    block: 'blok-1',
    title: 'Wetenschapsfilosofie — Blok 1',
    sources,
    sourceNote: 'Gebaseerd op alle aangeleverde bestanden. De literatuur is een samenvatting; de oorspronkelijke publicaties zijn niet aanwezig. Screenshots bevatten de Week 1 Quiz, geen volledig proefexamen. Nieuwe casussen zijn oefenvarianten, geen officiële examenvragen.',
    settings: { batchSize: 7, mixed: true, intervalsDays: [1,3,5,8,11,14], maxIntervalDays: 14, wrongAnswer: 'feedback-then-append', resetOnWrong: true },
    items: [
      ...flashcards.map((r,i) => ({id: 'b1-f-'+String(i+1).padStart(3,'0'), block:'blok-1', type:'flashcard', topic:r[0], question:r[1], answer:r[2], source:r[3]})),
      ...quizzes.map((r,i) => ({id: 'b1-q-'+String(i+1).padStart(3,'0'), block:'blok-1', type:'quiz', topic:r[0], question:r[1], options:r[2], correctIndex:0, explanation:r[3], source:r[4]}))
    ]
  };
  if (typeof module !== 'undefined' && module.exports) module.exports = bank;
  else root.BLOK_1 = bank;
})(typeof globalThis !== 'undefined' ? globalThis : this);

